/* Autogenerated by hxtools bin2c */
#ifndef FONT_16X8_H
#define FONT_16X8_H 1

#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned char bin2c_font_16x8_fnt[4096];

#ifdef __cplusplus
} /* extern "C" */
#endif


#endif /* FONT_16X8_H */
